# Config file for Qud Blueprint Explorer
App name: Qud Blueprint Explorer
Wiki name: >-
  [[Qud Blueprint Explorer|QBE]]
Version: v1.0rc1

Interface:
  # Interface options
  Initial expansion targets:
    # These object category IDs will be expanded when the tree is initialized:
    [Food, MeleeWeapon, MissileWeapon, Armor, Shield, Token, LightSource, Tool, Tonic, Trinket,
     Energy Cell, Barathrumite, SapientMutatedFlower]

Templates:
  # Options controlling the generation of wiki infobox templates
  Fields:
    # The fields that (if applicable) will be generated for each item, in this order:
    # (title comes first, but is not listed here)
    [title, image, pv, maxpv, vibro, pvpowered, damage, unpowereddamage, lv, hp, av, dv, ma, tohit, ammo,
     accuracy, shots, maxammo, maxvol, liquidgen, liquidtype, maxcharge, chargeperdram, chargeused,
     weight, commerce, complexity, tier, bits, canbuild, candisassemble, empsensitive, skill, colorstr, renderstr,
     id, bookid, lightradius, hunger, thirst, healing, butcheredinto, harvestedinto, preservedinto,
     preservedquantity, cookeffect, ismeat, isplant, isfungus, exoticfood, illoneat, corpse, corpsechance, twohanded, metal, lightprojectile, reflect, movespeed, cursed, role, destroyonunequip, savemodifier, savemodifieramt, extra, strength,
     agility, toughness, intelligence, willpower, ego, acid, electric, cold, heat, poison,
     reputationbonus, faction, wornon, usesslots, gender, pronouns, desc, eatdesc]
  Image overrides:
    # Manually specify the image name to be shown for an object ID:
    Asphodel: Earl_asphodel.png
    Lulihart, Hindren Pariah: Lulihart.png
    Across1: across moghrayi.png
    Across2: across moghrayi.png
    Across3: across moghrayi.png


Wiki:
  # See also wiki login configuration in wiki.yml.
  Article overrides:
    # Manually specify the article title to be used for an object ID:
    # Example:
    ClockworkBeetle: Clockwork Beetle
    Torch: Torch
    MerchantAdvertisement: Advertisement

  Article black+whitelist categories:
    # Categories, or individual articles, to include or exclude from consideration for
    # wiki operations (can still generate templates for them, just not scan or upload).
    # For things that really shouldn't get wiki articles, like data buckets.
    # Later lines override earlier ones, so to include, for example, only Hindren in the wiki,
    # you could blacklist Object then whitelist BaseHindren.
    # BaseObjects are already restricted from wiki action, since they can't be selected.
    # Objects with no DisplayName or with [ in their DisplayName are already restricted.
    #
    # Lines starting with * whitelist a category.
    #   "      "      "   / blacklist a category.
    #   "      "      "   + whitelist a single object
    #   "      "      "   - blacklist a single object.
    [
      /DataBucket,
      -Starch,
      -Lignin,
      -Clue_YuckwheatChaff,
      -Clue_SeveredTongue,
      /GenericLimb,
      /PlantLimb,
      /FungusLimb,
      /Corpse,
      +Albino Ape Pelt,
      +Albino Ape Heart,
      +Black Puma Haunch,
      -ExileCorpse,  # extraneous
      -JoppaCorpse,  # extraneous
      +Ogre Ape Heart,
      -Bones,
      +Crystal of Eve,
      +Arsplice Seed,
      /RobotLimb,
      /TemporaryProjectile,
      -Clue_SplinteredWeaponHaft,
      -Clue_BloodyArrow,
      -MjoFemur,
      -MjoLeg,
      -Flail,
      -Chain,
      -TestSword,
      -CacheFlamethrower,
      /NaturalMissileWeapon,
      -Carapace,
      /Quills,
      -Wings,
      -Stinger,
      -Ghostly Flames,
      -Icy Vapor,
      -Horticulturalist Bio-Scanning Bracelet,
      -Child of the Deep Structural Scanning Bracelet,
      /BaseBeadBracelet,
      +Bracelet1,  # just including one bracelet from BaseBeadBracelet
      -Fork-Horned Helmet 4,  # was an experimental item
      -Clue_DiscardedBracer,
      -Clue_WornBracer,
      -Scaled Helmet,
      -Gesticulators,
      -TestShockGlove,
      -Clue_BloodyPatchOfFur,
      -Clue_LeatherScraps,
      /NaturalWeapon,
      -BrokenSnailmotherEgg,
      -SnailmotherEgg,
      -DummyTinkerScreenObject,
      -hologram of Shekhinah,
      -Brazier,
      -Tall Brazier,
      /Vessel,
      -RandomFactionDeed,
      /BaseCookbook,
      /RandomBook,
      -Plant Turret,
      -PaintTest,
      /CosmeticObject
    ]

  Categories:
    # Each wiki category is followed by a list of nodes in the inheritance tree whose child objects
    # should be in that category. Objects may also be explicitly specified.
    # Order matters since later, more specific entries can override earlier, more general ones.
    Items: [Item]
    Weapons: [MeleeWeapon, MissileWeapon]
    Melee Weapons: [MeleeWeapon]
    Ammo: [Projectile]
    Cudgels: [BaseCudgel]
    Daggers: [BaseDagger]
    Axes: [BaseAxe]
    Long Blades: [BaseLongBlade]
    Missle Weapons: [MissileWeapon]
    Natural Weapons: [NaturalWeapon]
    Firearms: [BaseFirearm]
    Pistols: [BasePistol]
    Rifles: [BaseRifle]
    Heavy Weapons: [BaseHeavyWeapon]
    Bows: [BaseBow]
    Equipment: [Armor, Shield]
    Bracelets: [BaseBracelet]
    Helmets: [BaseHelmet]
    Hats: [BaseHat]
    Masks: [BaseMask]
    Facial Jewelry: [BaseFaceJewelry]
    Armlets: [BaseArmlet]
    Armor: [BaseArmor]
    Shields: [BaseShield]
    Boots: [BaseBoot]
    Gloves: [BaseGlove]
    Cloaks: [BaseCloak]
    Tokens: [Token]
    Light Sources: [Glowsphere, Floating Glowsphere, Quantum Mote, Torch, Luminous Mote,
                    Kindleflame, Symbiotic Firefly]
    Energy cells: [Energy Cell]
    Thrown Weapons: [BaseThrownWeapon]
    Trinkets: [Trinket]
    Food: [Food]
    Books: [Book]
    Preserved Food: [Preservable]
    Tools: [Tool]
    Tonics: [Tonic]
    Water Containers: [WaterContainer]
    Trade Goods: [Copper Nugget, Silver Nugget, Gold Nugget, Gemstone, Bronze Ingot, BoxOfCrayons,
                  Polyhedral Rings, Silver Rondure, Blood-stained neck-ring]
    Plants: [Plant]
    Creatures: [Creature]
    Unique Characters: [Phinae Hoshaiah, Barathrumite, Argyve, ElderBob, Mehmet, Warden Ualraig,
                 Warden Esthers, Eskhind, Meyehind, Liihart, Isahind, Neelahind, Keh, Kesehind,
                 Angohind, Lulihart, AgateSeveranceStar, Mayor Nuntu, Oboroqoru, Asphodel, Yurl,
                 Euclid]
