# Config file for Qud Blueprint Explorer
App name: Qud Blueprint Explorer
Wiki name: >-
  [[Qud Blueprint Explorer|QBE]]
Version: v1.0rc1

Interface:
  # Interface options
  Initial expansion targets:
    # These object category IDs will be expanded when the tree is initialized:
    [Food, MeleeWeapon, MissileWeapon, Armor, Shield, Token, LightSource, Tool, Tonic, Trinket,
     Energy Cell, Barathrumite, SapientMutatedFlower]

Templates:
  # Options controlling the generation of wiki infobox templates
  Fields:
    # The fields that (if applicable) will be generated for each item, in this order:
    # (title comes first, but is not listed here)
    [title, image, pv, maxpv, vibro, pvpowered, damage, unpowereddamage, lv, hp, av, dv, ma, tohit, ammo,
     accuracy, shots, maxammo, maxvol, liquidgen, liquidtype, maxcharge, chargeperdram, chargeused,
     weight, commerce, complexity, tier, bits, canbuild, candisassemble, empsensitive, skill, colorstr, renderstr,
     id, bookid, lightradius, hunger, thirst, healing, butcheredinto, harvestedinto, preservedinto,
     preservedquantity, cookeffect, ismeat, isplant, isfungus, exoticfood, corpse, corpsechance, twohanded, metal, lightprojectile, reflect, cursed, role, extra, strength,
     agility, toughness, intelligence, willpower, ego, acid, electric, cold, heat, poison,
     reputationbonus, faction, wornon, usesslots, gender, pronouns, desc, eatdesc]
  Image overrides:
    # Manually specify the image name to be shown for an object ID:
    Asphodel: Earl_asphodel.png

Wiki:
  Article overrides:
    # Manually specify the article title to be used for an object ID:
    # Example:
    ClockworkBeetle: Clockwork Beetle
    Torch: Torch

  Categories:
    # Each wiki category is followed by a list of nodes in the inheritance tree whose child objects
    # should be in that category. Objects may also be explicitly specified.
    # Order matters since later, more specific entries can override earlier, more general ones.
    Items: [Item]
    Weapons: [MeleeWeapon, MissileWeapon]
    Melee Weapons: [MeleeWeapon]
    Ammo: [Projectile]
    Cudgels: [BaseCudgel]
    Daggers: [BaseDagger]
    Axes: [BaseAxe]
    Long Blades: [BaseLongBlade]
    Missle Weapons: [MissileWeapon]
    Natural Weapons: [NaturalWeapon]
    Firearms: [BaseFirearm]
    Pistols: [BasePistol]
    Rifles: [BaseRifle]
    Heavy Weapons: [BaseHeavyWeapon]
    Bows: [BaseBow]
    Equipment: [Armor, Shield]
    Bracelets: [BaseBracelet]
    Helmets: [BaseHelmet]
    Hats: [BaseHat]
    Masks: [BaseMask]
    Facial Jewlery: [BaseFaceJewelry]
    Armlets: [BaseArmlet]
    Boots: [BaseBoot]
    Gloves: [BaseGlove]
    Cloaks: [BaseCloak]
    Energy cells: [Energy Cell]
    Thrown Weapons: [BaseThrownWeapon]
    Trinkets: [Trinket]
    Food: [Food]
    Preserved Food: [Preservable]
    Tools: [Tool]
    Tonics: [Tonic]
    Trade Goods: [Copper Nugget, Silver Nugget, Gold Nugget, Gemstone, Bronze Ingot, BoxOfCrayons,
                  Polyhedral Rings, Silver Rondure, Blood-stained neck-ring]
    Plants: [Plant]
    Creatures: [Creature]
    Unique Characters: [Phinae Hoshaiah, Barathrumite, Argyve, ElderBob, Mehmet, Warden Ualraig,
                 Warden Esthers, Eskhind, Meyehind, Liihart, Isahind, Neelahind, Keh, Kesehind,
                 Angohind, Lulihart, AgateSeveranceStar, Mayor Nuntu, Oboroqoru, Asphodel, Yurl,
                 Euclid]
