# Config file for Qud Blueprint Explorer
App name: Qud Blueprint Explorer
Wiki name: >-
  [[Qud Blueprint Explorer|QBE]]
Version: v1.0rc1

Interface:
  # Interface options
  Initial expansion targets:
    # These object category IDs will be expanded when the tree is initialized:
    [Food, MeleeWeapon, MissileWeapon, Armor, Shield, Token, LightSource, Tool, Tonic, Trinket,
     Energy Cell, Barathrumite, SapientMutatedFlower]

Templates:
  # Options controlling the generation of wiki infobox templates
  Fields:
    # The fields that (if applicable) will be generated for each item, in this order:
    # (title comes first, but is not listed here)
    [title, image, pv, maxpv, vibro, pvpowered, damage, unpowereddamage, lv, hp, av, dv, ma, tohit,
     ammo, accuracy, shots, maxammo, maxvol, liquidgen, liquidtype, maxcharge, chargeperdram,
     chargeused, weight, commerce, complexity, tier, bits, canbuild, candisassemble, empsensitive,
     skill, colorstr, renderstr, id, bookid, lightradius, hunger, thirst, healing, butcheredinto,
     harvestedinto, preservedinto, preservedquantity, cookeffect, ismeat, isplant, isfungus,
     exoticfood, illoneat, corpse, corpsechance, twohanded, metal, lightprojectile, reflect,
     movespeed, cursed, role, destroyonunequip, savemodifier, savemodifieramt, extra, strength,
     agility, toughness, intelligence, willpower, ego, acid, electric, cold, heat, poison,
     reputationbonus, faction, wornon, usesslots, gender, pronouns, desc, eatdesc]
  Image overrides:
    # Manually specify the image name to be shown for an object ID:
    Asphodel: Earl_asphodel.png
    Lulihart, Hindren Pariah: Lulihart.png
    Across1: across moghrayi.png
    Across2: across moghrayi.png
    Across3: across moghrayi.png
    Lyngbaskr: Lyngbaskr.png
    Porphyryptus: Porphyryptus.png
    either: either.png
    or: or.png
    Ebenshabat: Ebenshabat.png
    Shem -1: shem-1.png
    High Priest Eschelstadt: eschelstadt ii.png
    Phinae Hoshaiah: phinae hoshaiah.png
    Mamon: Mamon souldrinker.png
    Svenlainard: svenlainard.png

Wiki:
  # See also wiki login configuration in wiki.yml.
  Article overrides:
    # Manually specify the article title to be used for an object ID:
    # Example:
    MasterworkCarbine: Scoped masterwork carbine
    ClockworkBeetle: Clockwork beetle
    Torch: Torch
    MerchantAdvertisement: Advertisement
    Argyve's Data Disk: Argyve's data disk
    SingleSkillsoft1: Skillsoft (low SP)
    SingleSkillsoft2: Skillsoft (medium SP)
    Schemasoft2: Schemasoft (low-tier)
    SingleSkillsoft3: Skillsoft (high SP)
    TreeSkillsoft: Skillsoft (whole skill tree)
    Schemasoft3: Schemasoft (mid-tier)
    Schemasoft4: Schemasoft (high-tier)
    BethesdaBaetyl: Baetyl (Bethesda Susa)
    OasisGlowpad: oddly-hued glowpad
    Molting Basilisk: Molting basilisk
    Warden Indrix: Warden Indrix
    Svenlainard: Svenlainard
    AppleMerchant: apple farmer (merchant)
    DoorSwitch: control switch (door)
    ElevatorSwitch: control switch (elevator)
    TempleSwitch: control switch (temple)

  Article black+whitelist categories:
    # Categories, or individual articles, to include or exclude from consideration for
    # wiki operations (can still generate templates for them, just not scan or upload).
    # For things that really shouldn't get wiki articles, like data buckets.
    # Later lines override earlier ones, so to include, for example, only Hindren in the wiki,
    # you could blacklist Object then whitelist BaseHindren.
    # BaseObjects are already restricted from wiki action, since they can't be selected.
    # Objects with no DisplayName or with [ in their DisplayName are already restricted.
    #
    # Lines starting with * whitelist a category.  (* line needs to be wrapped with "" due to YAML)
    #   "      "      "   / blacklist a category.
    #   "      "      "   + whitelist a single object
    #   "      "      "   - blacklist a single object.
    [
      /DataBucket,
      -Starch,
      -Lignin,
      /GenericLimb,
      /PlantLimb,
      /FungusLimb,
      /Corpse,
      +Human Corpse,
      +Charred Corpse,
      +Mangled Corpse,
      +Ancient Corpse,
      +Fresh Corpse,
      +Moldering Corpse,
      +Albino Ape Pelt,
      +Albino Ape Heart,
      +Black Puma Haunch,
      -ExileCorpse,  # extraneous
      -JoppaCorpse,  # extraneous
      +Ogre Ape Heart,
      -Bones,
      +Crystal of Eve,
      +Arsplice Seed,
      /RobotLimb,
      /TemporaryProjectile,
      -MjoFemur,
      -MjoLeg,
      /Dagger,
      +Dagger,
      /Dagger3,
      +Dagger3,
      -Flail,
      -Chain,
      -TestSword,
      -CritPistol,
      -CacheFlamethrower,
      /NaturalMissileWeapon,
      -Carapace,
      /Quills,
      -Wings,
      -Stinger,
      -Ghostly Flames,
      -Icy Vapor,
      -Horticulturalist Bio-Scanning Bracelet,
      -Child of the Deep Structural Scanning Bracelet,
      /BaseBeadBracelet,
      +Bracelet1,  # just including one bracelet from BaseBeadBracelet
      -Fork-Horned Helmet 4,  # was an experimental item
      -Scaled Helmet,
      -Gesticulators,
      -TestShockGlove,
      /NaturalWeapon,
      -BrokenSnailmotherEgg,
      -SnailmotherEgg,
      -DummyTinkerScreenObject,
      -hologram of Shekhinah,
      -Brazier,
      -Tall Brazier,
      /Vessel,
      +Vase,
      +Bottle,
      +Pitcher,
      +Ewer,
      +Jug,
      +Long Jug,
      -RandomFactionDeed,
      /BaseCookbook,
      /RandomBook,
      /Waterskin,
      +Waterskin,
      +Clue_BulgingWaterskin,
      /Canteen,
      +Canteen,
      /Phial,
      +Phial,
      -Blank Recoiler,
      /Random Figurine,
      -Jewel-Encrusted Item,
      -Wire Strand 1,
      -Wire Strand 3,
      -Wire Strand 10,
      -Wire Strand 20,
      -Wire Strand 50,
      -Grit Gate Dormant Waydroid,
      -Drained Chem Cell,
      -Full Combustion Cell,
      -Klanq Garbage,
      /Marble Dais,
      /BaseCyberneticsCreditWedge,
      +CyberneticsCreditWedge,  # needs explanatory article for types
      -Village Hologram 2,
      -MetalWallWithPipes,
      -MainframeWall,
      -LowSandstoneWall,
      -BasaltWithPipes,
      /Marble,
      +Marble,
      +SixDayStiltPillarWall1,
      /Fulcrete,
      +Fulcrete,
      -GodcapMushroomFlesh2,
      -MushroomFlesh,
      -MushroomFlesh2,
      /GlassWall,
      +GlassWall,
      -Walltrap,
      /CryochamberWall,
      +CryochamberWall,
      -CryochamberWallBroken,
      /CryochamberPlaque,
      +CryochamberPlaque,
      -GritGateBroadcastPowerStation,
      -GritGateFusionPowerStation,
      -GritGateFusionPumpingStation,
      -GritGateHydraulicIrrigator,
      /GritGateForceProjector,
      -Torchpost,  # covered by Sconce, 'torch sconce'
      -Unlit Torchpost,  # ditto
      -Techlight2,  # covered by Techlight1, 'arc sconce'
      -Techlight3,  # ditto
      -Candelabra,  # covered by Half Candelabra, 'candelabra'
      /Wormhole,
      +Wormhole,
      /Door,
      +Gate,
      +Security Door,
      +Autodoor,
      -Woodfloor,
      -Grit Gate Sleek Table,
      -JoppaTable,
      -NuntuTable,
      -GunsmithTable,
      -Grit Gate Table,
      -Barathrum Table,
      -Klanq Table,
      -GritGatePowerLine,
      -GritGateHeavyPowerLine,
      -GritGateGlassHydraulicPipe,
      -GritGateChair,
      -GritGateCanvasFoldingChair,
      -GritGateMedicalChair,
      -GritGateWorkChair,
      -GritGateChairBear,
      -GritGateHyperbioticChair,
      -GritGateBed,
      -GritGateMedicalBed,
      -GritGateHyperbioticBed,
      /Oven,
      +Oven,
      -Preserved Food Basket,
      /Bookshelf,
      +Bookshelf,
      /Random Statue,
      /Chest,  # needs a lot of explanation in an article!
      +Chest,
      +WedgeChest1,  # needs explanatory article for 5 types
      +FossilizedRemains,
      +RustLocker,
      +MedLocker,
      "*Weapon Rack",
      +CyberneticsRack,
      +Clue_VillageStores,
      /Tombstone,
      +Tombstone,
      /Sign,  # needs article with all the sign tiles in it
      +AppleSign1,
      /SultanShrine,  # needs explanatory article
      -Switch,  # Switch itself is a BaseObject but not labeled as such
      -DisabledSwitch,  # cover in ElevatorSwitch article
      /Alchemist Table,
      +Alchemist Table,
      /Relief,  # needs art article combining tiles
      -StairsDownBarathrumsStudy,
      -GritGateMainframeRoomCommPanel,
      -PoisonGas80,
      -StableCryoGas,
      /AcidGas,
      +AcidGas,
      /StunGas,
      +StunGas,
      /SleepGas,
      +SleepGas,
      /ConfusionGas,
      +ConfusionGas,
      /NormalityGas,
      +NormalityGas,
      -FungalSporeGasLuminous,
      -FungalSporeGasPuff,
      -FungalSporeGasWax,
      -FungalSporeGasMumbles,
      -Space-Time Rift,
      # Plants
      -Godsbrush,
      -LiquidLichen,
      -LiquidLichen Minor,
      -FungusPuffer,
      -Shimscale Mangrove Tree_blue,
      -Dogthorn Tree2,
      -Fracti2,
      -Fracti3,
      -Starapple Farm Tree,
      -Swarmshade Tree_blue,
      -Tanglewood Tree_blue,
      -Spotted Shagspook 2,
      # Creatures
      /Ray Cat,
      +Ray Cat,
      +Ctesiphus,
      -Farm Goat,
      -Goatfolk Hero 1,
      -Farm Beetlebum,
      -Farm Giant Beetle,
      -PackTester,
      -Farm Eyeless Crab,
      -Eyeless King Crab Hero,
      -Farm GiantAmoeba,
      -RedrockGirshling,
      -Phase Spider Coward,
      -Farm Electric Snail,
      -Lyngbaskr,
      -Porphyryptus,
      -either,
      -or,
      -Ebenshabat,
      -Farm Leech,
      -TestDummy,
      # Robots
      -Sleeping Chromeling,
      -Sleeping Plated Chromeling,
      -Chrome Idol Hero 1,
      -Chrome Idol Hero Crazed,
      /GritGateChainLaserEmplacement,
      -Sleeping Waydroid,
      # Humanoids
      -Uplifted Knight Commander,
      -Missile Cannibal,
      /DromadTrader,
      +DromadTrader1,  # needs explanatory article of 8 varieties
      +Doru,  # Tam
      -Glow-Wight Hero of Agolgut 1,
      -Glow-Wight Hero of Bethsaida 1,
      -RedrockZealot,
      -JoppaZealot,
      -Snapjaw,
      -Snapjaw Dodger,
      -Snapjaw Rocketeer,
      -Snapjaw Laser,
      -InjectorSnapper,
      -CyberSnapper,
      /Snapjaw Warlord,
      +Snapjaw Warlord,
      -Snapjaw Packlord,
      -Wof,
      -Tabula Rasa,  # needs hand-edited article
      -BaseIssachari,
      -Mechanimist Pilgrim Still,
      -Six Day Choraler,
      -Mechanimist Preacher 2,
      -Mechanimist Preacher 3,
      -Mechanimist Preacher 4,
      -TestPax,
      -TestShopper,
      -TestPilgrim,
      # NPCs
      /BaseArconaut,
      +Arconaut,
      /Barathrumite_FactionMemberMale,
      +Barathrumite_FactionMemberMale,
      -OthoCopy,
      -MafeoCopy,
      /BaseWatervineFarmer,
      +WatervineFarmer,
      -StiltPigFarmer,
      -LoudSixDayZealot,
      -StiltChef,
      -Village Crier,
      -BaseBaboon,
      -Baboon Hero 1,
      -BetaPlant,
      -Plant Turret,
      -PaintTest,
      # CosmeticObjects
      /CosmeticObject,
      /Water,
      /Terrain,
      +Clue_Putrescence
    ]

  Categories:
    # Each wiki category is followed by a list of nodes in the inheritance tree whose child objects
    # should be in that category. Objects may also be explicitly specified.
    # Order matters since later, more specific entries can override earlier, more general ones.
    Items: [Item]
    Weapons: [MeleeWeapon, MissileWeapon]
    Melee Weapons: [MeleeWeapon]
    Ammo: [Projectile]
    Cudgels: [BaseCudgel]
    Daggers: [BaseDagger]
    Axes: [BaseAxe]
    Long Blades: [BaseLongBlade]
    Missle Weapons: [MissileWeapon]
    Natural Weapons: [NaturalWeapon]
    Firearms: [BaseFirearm]
    Pistols: [BasePistol]
    Rifles: [BaseRifle]
    Heavy Weapons: [BaseHeavyWeapon]
    Bows: [BaseBow]
    Equipment: [Armor, Shield]
    Bracelets: [BaseBracelet]
    Helmets: [BaseHelmet]
    Hats: [BaseHat]
    Masks: [BaseMask]
    Facial Jewelry: [BaseFaceJewelry]
    Armlets: [BaseArmlet]
    Armor: [BaseArmor]
    Shields: [BaseShield]
    Boots: [BaseBoot]
    Gloves: [BaseGlove]
    Cloaks: [BaseCloak]
    Tokens: [Token]
    Light Sources: [Glowsphere, Floating Glowsphere, Quantum Mote, Torch, Luminous Mote,
                    Kindleflame, Symbiotic Firefly]
    Energy cells: [Energy Cell]
    Liquid Fueled Energy Cells: [Liquid Fueled Energy Cell]
    Thrown Weapons: [BaseThrownWeapon, Geomagnetic Disc, ThrowingAxe, CastNet, SmallBoulder,
                     MediumBoulder, LargeBoulder]
    Trinkets: [Trinket]
    Scrap: [Scrap]
    Recoilers: [BaseRecoiler]
    Applicators: [Fixit Spray, Spraybottle, Metamorphic Polygel, Desalination Pellet, Bandage,
                  Spray-a-Brain]
    Food: [Food]
    Books: [Book]
    Preserved Food: [Preservable]
    Tools: [Tool]
    Tonics: [Tonic]
    Water Containers: [WaterContainer]
    Trade Goods: [Copper Nugget, Silver Nugget, Gold Nugget, Gemstone, Bronze Ingot, BoxOfCrayons,
                  Polyhedral Rings, Silver Rondure, Blood-stained neck-ring]
    Plants: [Plant]
    Creatures: [Creature]
    Dogs: [BaseDog]
    Robots: [BaseRobot] #any creatures that are in the Robots faction will be categorized with [[Robots (Faction)]]
    Bears: [BaseBear]
    Snapjaws: [BaseSnapjaw]
    Humanoids: [BaseHumanoid]
    Issachari: [BaseIssachari]
    Cragmensch: [Cragmensch]
    Naphtaali: [BaseNaphtaali]
    Insects: [BaseInsect]
    Mechanimists: [BaseMechanimist]
    Reptiles: [BaseReptile]
    Goatfolk: [Goatfolk]
    Oozes: [BaseOoze]
    Tortoises: [BaseTortoise]
    Frogs: [Ice frog,Bloated Pearlfrog]
    Fish: [BaseFish]
    Spiders: [BaseSpider]
    Worms: [BaseWorm]
    Snails: [BaseSnail]
    Slugs: [BaseSlug]
    Merchants: [BaseMerchant]
    Unique Characters: [Phinae Hoshaiah, Argyve, ElderBob, Mehmet, Warden Ualraig,
                 Warden Esthers, Eskhind, Meyehind, Liihart, Isahind, Neelahind, Keh, Kesehind,
                 Angohind, Lulihart, AgateSeveranceStar, Mayor Nuntu, Oboroqoru, Asphodel, Yurl,
                 Euclid, Warden Indrix, Mamon, Svenlainard, Otho, Q Girl, Barathrum, Sparafucile,
                 Jacobo, Dardi, Hortensa, Iseppa, Neek, Mafeo, Aloysius, High Priest Eschelstadt,
                 Troll King 1, Troll King 2, Troll King 3, Doru, Rodanis Y, Shem -1,
                 GolgothaSlog, Ctesiphus,OasisGlowpad]
    Quest Items: [Scrapped Waydroid, Scratch Data Disk, Stamped Data Disk, Argyve's Data Disk,
                  Argyve's Data Disk Encoded, ClimberBlueprints, Dormant Waydroid, BarathrumKey,
                  Clue_YuckwheatChaff, Clue_SeveredTongue, Clue_SplinteredWeaponHaft,
                  Clue_BloodyArrow, Clue_DiscardedBracer, Clue_WornBracer, Clue_BloodyPatchOfFur,
                  Clue_LeatherScraps, Clue_CopperNugget, Clue_BulgingWaterskin, Clue_VillageStores,
                  Gnawed Watervine, Clue_BloodyWatervine]